version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
      python: 3.11
    commands:
      - echo Installing Terraform...
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version

  build:
    commands:
      - echo Running Terraform Init...
      - terraform init

      - echo Running Terraform Plan...
      - |
        terraform plan -out=tfplan || {
          echo "Terraform Plan failed. Sending alert...";
          aws sns publish \
            --topic-arn arn:aws:sns:ap-south-1:860265990835:my-react-app-terraform-failures \
            --subject "Terraform Plan Failed in CodeBuild" \
            --message "Terraform plan failed for my-react-app in CodeBuild. Please check the logs.";
          exit 1;
        }

      - echo Running Terraform Apply...
      - |
        terraform apply -auto-approve tfplan || {
          echo "Terraform Apply failed. Sending alert...";
          aws sns publish \
            --topic-arn arn:aws:sns:ap-south-1:860265990835:my-react-app-terraform-failures \
            --subject "Terraform Apply Failed in CodeBuild" \
            --message "Terraform apply failed for my-react-app in CodeBuild. Please check the logs.";
          exit 1;
        }

artifacts:
  files:
    - '**/*'
