version: 0.2

env:
  variables:
    BUILD_DIR: "build"
    S3_DEST_PATH: "/"
    # Your hardcoded values (tested for your account)
    TF_FAILURE_TOPIC: "arn:aws:sns:ap-south-1:860265990835:my-react-app-terraform-failures"
    DEPLOYMENT_ENV: "production"
    PROJECT_REPO: "https://github.com/ankitkanojia786/Deploying-a-React-Application-with-CI-CD"
    CLOUDFRONT_URL: "https://d1bh10607ak6rt.cloudfront.net"
    BUILD_TIMESTAMP: $(date +%Y-%m-%dT%H:%M:%S%z)

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # =============================================
      # TEST NOTIFICATION (REMOVE AFTER CONFIRMATION)
      # =============================================
      - echo "Sending test alert to verify email setup..."
      - aws sns publish \
          --topic-arn "$TF_FAILURE_TOPIC" \
          --subject "[ALERT TEST] Email System Check - ${APP_NAME}" \
          --message "This is a TEST alert to confirm your email (ankitkanojia58@gmail.com) can receive notifications.
          
          APP: ${APP_NAME}
          ACCOUNT: 860265990835
          REGION: ap-south-1
          CLOUDFRONT URL: ${CLOUDFRONT_URL}
          
          If you receive this, your alert system is working!"
      
      # Install dependencies
      - npm ci
      - terraform --version
      - aws --version

  pre_build:
    commands:
      - export BUILD_URL="https://ap-south-1.console.aws.amazon.com/codesuite/codebuild/860265990835/projects/${APP_NAME}-build/build/${APP_NAME}-build%3A${CODEBUILD_BUILD_ID}/?region=ap-south-1"
      - echo "Build Logs: ${BUILD_URL}"

  build:
    commands:
      # =============================================
      # SIMULATE FAILURE (UNCOMMENT TO TEST FAILURE)
      # =============================================
      # - echo "Simulating build failure..." && exit 1

      - |
        echo "Building React app..."
        npm run build 2>&1 | tee build.log || {
          ERROR_MSG="React build failed"
          ERROR_DETAILS=$(tail -n 15 build.log | sed 's/"/\\"/g')
          
          aws sns publish \
            --topic-arn "$TF_FAILURE_TOPIC" \
            --subject "[FAILURE] Build Failed - ${APP_NAME}" \
            --message "CRITICAL: React build failed!
            
            APP: ${APP_NAME}
            ENV: ${DEPLOYMENT_ENV}
            TIMESTAMP: ${BUILD_TIMESTAMP}
            REPO: ${PROJECT_REPO}
            BUILD LOGS: ${BUILD_URL}
            
            ERROR DETAILS:
            ${ERROR_DETAILS}"
          exit 1
        }

  post_build:
    commands:
      - |
        echo "Sending success notification..."
        aws sns publish \
          --topic-arn "$TF_FAILURE_TOPIC" \
          --subject "[SUCCESS] ${APP_NAME} Deployed!" \
          --message "Deployment successful!
          
          APP: ${APP_NAME}
          ENV: ${DEPLOYMENT_ENV}
          TIMESTAMP: ${BUILD_TIMESTAMP}
          CLOUDFRONT URL: ${CLOUDFRONT_URL}
          BUILD LOGS: ${BUILD_URL}"
        
        echo "✅ Successfully deployed to: ${CLOUDFRONT_URL}"

artifacts:
  files:
    - '**/*'
  base-directory: "$BUILD_DIR"
